News
WildCodeSchool/orleans-0219-php-escape pull request #14
Opened 2019-04-17 14:36 UTC by TortueNina

2019-04-18 05:50 UTC, sblondeau requested changes

2019-04-18 05:50 UTC, sblondeau commented on public/assets/css/style.css
> +@media screen and (max-width: 768px) {
meme remarque sur les media queries, à simplifier si possible

2019-04-18 05:50 UTC, sblondeau commented on src/View/Home/news.html.twig
> +                3 days ago
c'est normal qu'il y ait un bout de texte en anglais ici ?

2019-04-18 05:50 UTC, sblondeau commented on src/View/Home/news.html.twig
> +                7 days ago
idem, c'est pas sensé être dynamique cette valeur ?

2019-04-18 05:51 UTC, sblondeau requested changes

2019-04-18 05:51 UTC, sblondeau commented on src/View/Home/news.html.twig
> +                <p class="card-text">Nous serons là parmi vous pour ce super événement, le capitaine Wynne vous attend... Rendez vous le samedi 25 mai...</p>
ce sont des données administrables ces news non ? donc ça devrait venir d'une requete en BDD et non être écrit "en dur" ici

2019-04-23 09:57 UTC, TortueNina commented on src/View/Home/news.html.twig
> +                <p class="card-text">Nous serons là parmi vous pour ce super événement, le capitaine Wynne vous attend... Rendez vous le samedi 25 mai...</p>
Certes, c'est censé être dynamique mais c'est censé aussi utiliser l'API de twitter. Donc on a fait des mocks :)

2019-04-24 09:56 UTC, open-it requested changes

2019-04-24 09:56 UTC, open-it commented on src/View/layout.html.twig
> +{% block news %}
pas de block news dans le layout

2019-04-26 08:28 UTC, closed without merging