Ajout Cards Missions
WildCodeSchool/orleans-0219-php-escape pull request #45
Opened 2019-04-29 16:26 UTC by TortueNina

2019-04-29 20:33 UTC, sblondeau requested changes

2019-04-29 20:33 UTC, sblondeau commented on src/View/Home/_navbar.html.twig
> +                        <a class="dropdown-item" href="/Missions/index">Toutes les missions</a>
le dropdown doit se charger dynamiquement depuis la BDD

2019-04-29 20:33 UTC, sblondeau commented on src/View/Missions/_missions.html.twig
> +        <div class="row justify-content-center card-deck">
tu dois récup toutes les missions en BDD depuis ton controlleur (qui lui fait appel au MissionManager) et envoyer un tableau $missions dans ta vue
Ensuite dans le twig du boucle sur ton tableau et tu affiches toutes le missions via cette unique boucle (et donc tu ne répètes pas N fois l'HTML.

2019-04-30 11:52 UTC, sblondeau requested changes

2019-04-30 11:52 UTC, sblondeau commented on src/View/Home/_navbar.html.twig
>                          <a class="dropdown-item" href="#">Nautilus(VR)</a>
j'imagine que "Nautilus, Lademeure, etc. sont des noms de mission. Ton dropdown doit donc être construit dynamiquement en fonction du contenu de ta table missions...

2019-04-30 11:52 UTC, sblondeau commented on src/View/Missions/index.html.twig
> +                                    <p class="card-text col"> Difficulté: </br>
la difficulté de la mission est une info dynamique également. Donc pas systématiquement à 4/5 comme ici.
il faut faire une boucle de 1 à 5 et afficher la classe checked ou non en fonction des besoins

2019-04-30 11:52 UTC, sblondeau commented on src/Model/MissionManager.php
> +    public function insert(array $mission): int
insert/delete/update en trop dans la PR

2019-04-30 12:53 UTC, open-it requested changes

2019-04-30 12:53 UTC, open-it commented on src/Controller/MissionController.php
> +        return $this->twig->render('Missions/index.html.twig', ['missions'=>$missions]);
c est mission sans S (comme le controller)

2019-04-30 12:53 UTC, open-it commented on src/View/Home/_missionButton.html.twig
> +        <h3><a href="/Mission/index">Missions</a></h3>
tu fais carrement une sous vue pour inclure un lien ??? Ca me parait exagéré

2019-04-30 12:53 UTC, open-it commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
ca m etonnerai que ce lien fonctionne !!

2019-04-30 12:55 UTC, TortueNina commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
Si il fonctionne !

2019-04-30 12:56 UTC, TortueNina commented on src/Controller/MissionController.php
> +        return $this->twig->render('Missions/index.html.twig', ['missions'=>$missions]);
Patoch m'a dit que je pouvais laisser celui ci avec le S

2019-04-30 12:57 UTC, TortueNina commented on src/View/Home/_missionButton.html.twig
> +        <h3><a href="/Mission/index">Missions</a></h3>
Il ne fonctionne pas le 1er href, j'ai essayé, il ne sait qu'ouvrir le dropdown (que je completerai dans une autre US) .........

2019-04-30 14:52 UTC, open-it requested changes
le dernier commit ne corrige pas le probleme des etoiles lié a une vieille version de font awesome

2019-04-30 16:38 UTC, open-it approved these changes

2019-04-30 16:38 UTC, merged