Navbar
WildCodeSchool/orleans-0219-php-escape pull request #8
Opened 2019-04-16 09:05 UTC by TortueNina

2019-04-16 09:59 UTC, sblondeau requested changes
les noms d'images devraient aussi etre en anglais si on veut être cohérent (par contre les "alt" en français bien sûr)

2019-04-16 09:59 UTC, sblondeau commented on src/View/Home/_navbar.html.twig
> +                    <div class="dropdown-menu active" aria-labelledby="navbarDropdownMenuLink">
tu ne dois avoir qu'un seul item de menu en "active", cette classe est sensé indiquer "où" tu te trouve dans le site en mettant en évidence l'item correspondant dans la navbar

2019-04-16 09:59 UTC, sblondeau commented on src/View/layout.html.twig
> +    <link rel="icon" href="/assets/images/navbar/logoprojet2.png">
vous avez deux favicon là

2019-04-16 09:59 UTC, sblondeau commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
ton fichier style devrait etre appelé AVANT le block stylesheet, pour que les feuilles CSS que tu ajouteras sur d'autres pages spécifiquement via ce bloc, puissent surcharger style.css

2019-04-17 12:58 UTC, sblondeau requested changes

2019-04-17 12:58 UTC, sblondeau commented on public/assets/css/style.css
> +@media screen and (max-width: 375px) {
pourquoi autant de media queries ? normalement bootrstrap gère une navbar responsive de base...

2019-04-23 10:11 UTC, open-it approved these changes

2019-04-23 15:38 UTC, open-it requested changes

2019-04-23 15:38 UTC, open-it commented on src/View/layout.html.twig
> +    {% block assets %}
il n'y a pas de block assets dans le layout (d'ailleurs qu'est il sensé contenir ?)

2019-04-23 15:38 UTC, open-it commented on src/View/layout.html.twig
> +    {% block news %}
pas de block news non plus. Il devrait  y avoir uniquement un block "content" qui va contenir le contenu de chaque page.

2019-04-23 15:38 UTC, open-it commented on src/View/layoutVisitor.html.twig
>  {% block content %}
vous faites référence ici à un block content qui n'existe pas dans le parent... Donc ca ne fonctionne pas... (mais pourtant ca a été validé ?)

2019-04-24 09:45 UTC, open-it requested changes

2019-04-24 09:45 UTC, open-it commented on src/View/Home/assets.html.twig
> +<section>
je ne devrais pas avoir de modif de assets dans une PR sur navbar

2019-04-24 09:45 UTC, open-it commented on src/View/Home/assets.html.twig
> +                <div class="masque doliprane">
quelle est cette classe "doliprane" ??

2019-04-24 09:45 UTC, open-it commented on src/View/Home/header.html.twig
> +<header>
le fichier header si il est inclus devrait se nommer _header.html.twig et ne devrait pas etre présent sur une PR navbar

2019-04-24 09:45 UTC, open-it commented on src/View/Home/header.html.twig
> +<header>
balise header présent ici ET dans le layout !

2019-04-24 09:47 UTC, closed without merging